import{a as b,S as q,i as n}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const v="https://pixabay.com/api/",$="47301858-8ff081a19a6e75e487e16544c";async function d(o,r){return(await b.get(v,{params:{key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r}})).data}const p=document.querySelector(".gallery"),y=document.querySelector(".loader"),f=document.querySelector(".load-more"),E=new q(".gallery a");function m(o){const r=o.map(({webformatURL:s,largeImageURL:l,tags:e,likes:t,views:a,comments:L,downloads:S})=>`
      <li class="photo-card">
        <a href="${l}">
          <img src="${s}" alt="${e}" width="360" height="200" />
        </a>
        <ul class="props">
          <li>Likes <span class="props-value">${t}</span></li>
          <li>Views <span class="props-value">${a}</span></li>
          <li>Comments <span class="props-value">${L}</span></li>
          <li>Downloads <span class="props-value">${S}</span></li>
        </ul>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",r),E.refresh()}function B(){p.innerHTML=""}function h(){y.style.display="block"}function g(){y.style.display="none"}function M(){f.style.display="block"}function w(){f.style.display="none"}const P=document.querySelector(".form"),O=document.querySelector(".searchbar"),H=document.querySelector(".load-more");let i=1,c="",u=0;P.addEventListener("submit",async o=>{o.preventDefault();const r=O.value.trim();if(r===""){n.error({title:"Error",message:"Search query cannot be empty!"});return}c=r,i=1,B(),w(),h();try{const s=await d(c,i);if(u=s.totalHits,s.hits.length===0){n.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}m(s.hits),u>15&&M()}catch(s){n.error({title:"Error",message:`Something went wrong: ${s.message}`})}finally{g()}});H.addEventListener("click",async()=>{i+=1,h();try{const o=await d(c,i);m(o.hits);const{height:r}=document.querySelector(".photo-card").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),i*15>=u&&(w(),n.info({title:"End of Collection",message:"We're sorry, but you've reached the end of search results."}))}catch(o){n.error({title:"Error",message:`Something went wrong: ${o.message}`})}finally{g()}});
//# sourceMappingURL=index.js.map
